[package]
name = "liftd-backend"
version = "0.1.0"
authors = ["Martins <dzirko2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"